version: '3'
services:
  web:
    build: "./nginx"
    ports: 
      - "80:80"
    depends_on:
      - api
      - front
    # volumes:
    #   - ./frontend/build:/app/frontend/build
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ~/.aws:/root/.aws
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api