version: '3'
services:
  web:
    build: "./nginx"
    ports: 
      - "80:80"
    depends_on:
      - api
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
