name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      working-directory: ./API
      uses: actions/setup-go@v5.0.1
      with:
        stable: 'false'
        go-version: ${{ matrix.go-version }}

    - uses: actions/checkout@v4.1.4
      working-directory: ./API
    - name: Test
      working-directory: ./API
      run: go test ./...
